spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/hyperprof?useSSL=false&serverTimeZone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate:
        "[format_sql]"
